### ISSUE TITLE
Use a transpiler

### ISSUE THREAD

**Issue by robertpainsi** [Catrobat/deprecated_Jira_6.4.12_Timesheet#3]
[es6](http://es6-features.org) is one of the best things that has happened to JavaScript (the [`class`](https://medium.com/javascript-scene/how-to-fix-the-es6-class-keyword-2d42bb3f4caf) keyword is still arguable). Writing less, better and less error-prone code should always be a goal.

What about using a [transpiler](https://en.wikipedia.org/wiki/Source-to-source_compiler)? Maybe https://babeljs.io People are writing more and more [VanillaJS](http://vanilla-js.com) code because of it.

In some private projects of mine I'm also using the es7 features [await/async](https://jakearchibald.com/2014/es7-async-functions) which simplifies writing async code a lot as well.

Just a suggestion :wink:

**Comment by MarkusHobisch** [comment]
Maybe you are oneday at university than we could talk about it in detail.

**Comment by robertpainsi** [comment]
> Maybe you are oneday at university than we could talk about it in detail.

Sure, I'll let you know when I'm heading to Graz the next time (beginning of october) :wink:

**Comment by MarkusHobisch** [comment]
great ;)
