### ISSUE TITLE
Don't use synchronized (blocking) ajax calls

### ISSUE THREAD

**Issue by robertpainsi** [Catrobat/deprecated_Jira_6.4.12_Timesheet#4]
``` javascript
$.ajax({...
  async: false
});
```

`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/`

Use promises or callbacks.

**Comment by MarkusHobisch** [comment]
Yes you are alright. I fixed it.
